name:                gittar
version:             0.1.0.0
github:              "githubuser/gittar"
license:             MIT
author:              "Zhengyao Lin"
maintainer:          "zhengyao-lin@outlook.com"
copyright:           "2019 Zhengyao Lin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gittar#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2
- mtl >= 2.2.2
- containers >= 0.6.0.1
- cryptohash >= 0.11.9
- utf8-string >= 1.0.1.1
- directory >= 1.3.3.0
- unordered-containers >= 0.2.9.0
- hashable >= 1.2.6.1
- text >= 1.2.3.1
- ini >= 0.3.6
- filepath >= 1.4.2.1
- zlib >= 0.6.2
- time >= 1.8.0
- split >= 0.2.3.3
- word8 >= 0.1.3
- attoparsec >= 0.13.2.2

library:
  source-dirs: src

executables:
  gittar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gittar
